# Generated by Django 3.2.10 on 2022-01-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='short description')),
                ('long_desc', models.TextField(blank=True, null=True, verbose_name='long description')),
                ('photo', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('custom1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='category')),
            ],
        ),
    ]
