# Generated by Django 3.2.10 on 2022-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220121_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
